### ISSUE TITLE
Webmaster authentication system for submitting blog entries

### ISSUE THREAD

**Issue by david-zou** [Ryxias/react-hell#53]
I would like to propose an authentication system for the website so that webmasters can log in and submit blog entries without issues while preventing non-authorized users from being able to tamper the blog entries and the database.  I am currently looking into setting up a JWT based authentication with a login page on the site.  More details on how to set it up can be found on this site: 

https://vladimirponomarev.com/blog/authentication-in-react-apps-creating-components

---

First goal would be to get a log in page working and be able to submit the credentials in a properly packaged JSON object.  Obviously, before this happens this password will need to be salted before it gets to the database.  After that, I will be playing around with JWTs to get a session going that can persist even after hard reloading the page.

**Comment by Ryxias** [comment]
Veto—too advanced
